import {test} from '@playwright/test'
test ('Dropdown Handling' , async ({page}) =>{
    await page.goto('https://letcode.in/dropdowns')
    const fruits =  await page.locator('//select[@id="fruits"]')
    await fruits.selectOption({index:2})
    const singledropdown = await fruits.locator('option:checked').textContent()
    console.log(singledropdown)
    const superheros = await page.locator('//select[@id="superheros"]')
    await superheros.selectOption([{label:"Thor" },{index :3 }, {value:"im"} ])
    const multidropdown =  await superheros.locator('option:checked').allTextContents()
    console.log(multidropdown)
    const language = await page.locator('//select[@id="lang"]')
    await language.selectOption({label:"Python"})
    const drop= await language.locator('Option:checked').textContent()
    console.log(drop)
    const country = await page.locator('//select[@id="country"]')
    await country.selectOption( {value:"India"})
    const place= await country.locator('Option:checked').allTextContents()
    console.log(place)
})
